# ATAC-seq analysis configuration

# Sample information table
samples_table: "ref/samples.csv"

# Adapter sequences for trimming
adapter_r1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
adapter_r2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"

# Reference genome index for bowtie2
bowtie2_index: "ref/UCSC/genome"
genome_size: "ref/hg38.genome"

# Blacklist regions file
blacklist: "ref/hg38_blacklist_regions.bed"
